"use client"
// AUTO-GENERATED by scripts/gen-tools-map.mjs
// Run `npm run gen:tools` (or just start dev/build) to refresh after adding a tool.

import dynamic from "next/dynamic"
import type { ComponentType } from "react"

function LoadingDots() {
  return (
    <div className="flex flex-1 items-center justify-center py-24">
      <div className="flex gap-1.5">
        <span className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.3s]" />
        <span className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.15s]" />
        <span className="h-2 w-2 animate-bounce rounded-full bg-primary" />
      </div>
    </div>
  )
}

const loading = () => <LoadingDots />

/*
 * Every entry uses a static import path so webpack / Turbopack can create
 * individual code-split chunks — only the requested tool's JS is loaded.
 *
 * Tools that remain as iframe wrappers for now (complex canvas games):
 *   network-defense-game, password-cracking-simulator, password-quest,
 *   privacy-rpg, social-engineering-escape-room
 * All others are full React components sharing the design system.
 */
const TOOLS_MAP: Record<string, ComponentType> = {
  "blog": dynamic(() => import("@/components/tools/blog"), { loading }),
  "breach-timeline": dynamic(() => import("@/components/tools/breach-timeline"), { loading }),
  "browser-comparison": dynamic(() => import("@/components/tools/browser-comparison"), { loading }),
  "browser-fingerprint": dynamic(() => import("@/components/tools/browser-fingerprint"), { loading }),
  "certificate-decoder": dynamic(() => import("@/components/tools/certificate-decoder"), { loading }),
  "cheat-sheets": dynamic(() => import("@/components/tools/cheat-sheets"), { loading }),
  "dev-tools": dynamic(() => import("@/components/tools/dev-tools"), { loading }),
  "digital-signature-verifier": dynamic(() => import("@/components/tools/digital-signature-verifier"), { loading }),
  "dns-leak-test": dynamic(() => import("@/components/tools/dns-leak-test"), { loading }),
  "email-analyzer": dynamic(() => import("@/components/tools/email-analyzer"), { loading }),
  "exif-remover": dynamic(() => import("@/components/tools/exif-remover"), { loading }),
  "favorites": dynamic(() => import("@/components/tools/favorites"), { loading }),
  "glossary": dynamic(() => import("@/components/tools/glossary"), { loading }),
  "guide-privacy-101": dynamic(() => import("@/components/tools/guide-privacy-101"), { loading }),
  "guide-security-basics": dynamic(() => import("@/components/tools/guide-security-basics"), { loading }),
  "hash-generator": dynamic(() => import("@/components/tools/hash-generator"), { loading }),
  "ip-lookup": dynamic(() => import("@/components/tools/ip-lookup"), { loading }),
  "jwt-decoder": dynamic(() => import("@/components/tools/jwt-decoder"), { loading }),
  "link-safety-checker": dynamic(() => import("@/components/tools/link-safety-checker"), { loading }),
  "message-encryptor": dynamic(() => import("@/components/tools/message-encryptor"), { loading }),
  "minify-me": dynamic(() => import("@/components/tools/minify-me"), { loading }),
  // Canvas games — thin iframe wrappers
  "network-defense-game": dynamic(() => import("@/components/tools/network-defense-game"), { loading }),
  "password-cracking-simulator": dynamic(() => import("@/components/tools/password-cracking-simulator"), { loading }),
  "password-generator": dynamic(() => import("@/components/tools/password-generator"), { loading }),
  "password-manager-comparison": dynamic(() => import("@/components/tools/password-manager-comparison"), { loading }),
  "password-quest": dynamic(() => import("@/components/tools/password-quest"), { loading }),
  "phishing-quiz": dynamic(() => import("@/components/tools/phishing-quiz"), { loading }),
  "port-scanner": dynamic(() => import("@/components/tools/port-scanner"), { loading }),
  "privacy-policy-analyzer": dynamic(() => import("@/components/tools/privacy-policy-analyzer"), { loading }),
  "privacy-rpg": dynamic(() => import("@/components/tools/privacy-rpg"), { loading }),
  "privacy-score": dynamic(() => import("@/components/tools/privacy-score"), { loading }),
  "qr-code": dynamic(() => import("@/components/tools/qr-code"), { loading }),
  "rsa-key-generator": dynamic(() => import("@/components/tools/rsa-key-generator"), { loading }),
  "security-trivia": dynamic(() => import("@/components/tools/security-trivia"), { loading }),
  "social-engineering-escape-room": dynamic(() => import("@/components/tools/social-engineering-escape-room"), { loading }),
  "ssl-checker": dynamic(() => import("@/components/tools/ssl-checker"), { loading }),
  "subnet-calculator": dynamic(() => import("@/components/tools/subnet-calculator"), { loading }),
  "timestamp-converter": dynamic(() => import("@/components/tools/timestamp-converter"), { loading }),
  "tool-history": dynamic(() => import("@/components/tools/tool-history"), { loading }),
  "tracker-blocker-test": dynamic(() => import("@/components/tools/tracker-blocker-test"), { loading }),
  "url-encoder": dynamic(() => import("@/components/tools/url-encoder"), { loading }),
  "uuid-generator": dynamic(() => import("@/components/tools/uuid-generator"), { loading }),
  "vendor-lock-in": dynamic(() => import("@/components/tools/vendor-lock-in"), { loading }),
  "vpn-comparison": dynamic(() => import("@/components/tools/vpn-comparison"), { loading }),
  "web-checker": dynamic(() => import("@/components/tools/web-checker"), { loading }),
  "webrtc-leak-test": dynamic(() => import("@/components/tools/webrtc-leak-test"), { loading }),
  "wifi-security-analyzer": dynamic(() => import("@/components/tools/wifi-security-analyzer"), { loading }),
}

export function ToolClientContent({ slug }: { slug: string }) {
  const Component = TOOLS_MAP[slug]
  if (!Component) {
    console.error(`ToolClientContent: no component registered for slug "${slug}"`)
    return null
  }
  return <Component />
}
